<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drl_navigation</name>
  <version>0.0.0</version>
  <description>DRL Navigation package for robot in Gazebo</description>
  <maintainer email="079bel078.sandeep@pcampus.edu.np">Sandeep</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_ros_py</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-gym</exec_depend>
  <exec_depend>python3-stable-baselines3</exec_depend>
  <exec_depend>python3-torch</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>